# Generated by Django 3.0.4 on 2020-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('telegram_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('birth_day', models.DateField()),
                ('iin', models.CharField(max_length=12, unique=True)),
                ('udv_number', models.CharField(max_length=30)),
                ('udv_date', models.DateField()),
                ('udv_place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('bank_card', models.IntegerField()),
                ('iban', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=20)),
                ('email_address', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_hr', models.BooleanField(default=False)),
            ],
        ),
    ]
