# Generated by Django 3.0.4 on 2020-03-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='iin',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='udv_number',
            field=models.CharField(max_length=30),
        ),
    ]
