# Generated by Django 3.0.4 on 2020-03-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200320_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='iban',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employees',
            name='udv_place',
            field=models.CharField(max_length=255),
        ),
    ]
